### ISSUE TITLE
demo.py

### ISSUE THREAD

**Issue by swaggywilliam** [hailanyi/CasA#28]
How to visualize the result please?
I used demo.py from openpcdet
```
Traceback (most recent call last):
  File "/home/project/CasA/tools/demo.py", line 113, in <module>
    main()
  File "/home/project/CasA/tools/demo.py", line 99, in main
    pred_dicts, _ = model.forward(data_dict)
ValueError: too many values to unpack (expected 2)
```

**Comment by xtdxlyy** [comment]
I also have the same question. Have you solved it? Meanwhile, I cannot find the label_2 or pred folder in testing set, which prevents me from using other visualization programs.
