### ISSUE TITLE
关于多卡训练！！！

### ISSUE THREAD

**Issue by Karkers** [hailanyi/CasA#31]
大佬你好，在我的设备上pcdet0.3版本似乎不能进行多卡训练，运行script文件后就没有响应了，但是最新版本的pcdet能够进行多卡训练，我的设备是8*3090！请问你遇到过这个问题吗！

**Comment by yu-tnt** [comment]
/pcdet/utils/common_utils.py中的init_dist_pytorch函数初始的过程注释掉一部分参数。如下：
    dist.init_process_group(
        backend=backend,
        # init_method='tcp://127.0.0.1:%d' % tcp_port,
        # rank=local_rank,
        # world_size=num_gpus
    )

**Comment by Karkers** [comment]
非常感谢，成功运行了！！！

**Comment by DietCoke5** [comment]
2024-10-10 21:24:50,763 INFO **********************Start training kitti_models/CasA-V(default)**********************
epochs: 0%| | 0/80 [00:00<?, ?it/s]
Traceback (most recent call last): | 0/1856 [00:00<?, ?it/s]
File "train.py", line 197, in <module>
main()
File "train.py", line 169, in main
merge_all_iters_to_one_epoch=args.merge_all_iters_to_one_epoch
File "/home/ly/test/CasA-master/CasA-master/tools/train_utils/train_utils.py", line 101, in train_model
dataloader_iter=dataloader_iter
File "/home/ly/test/CasA-master/CasA-master/tools/train_utils/train_utils.py", line 25, in train_one_epoch
batch = next(dataloader_iter)
File "/home/ly/anaconda3/envs/casa/lib/python3.6/site-packages/prefetch_generator/__init__.py", line 116, in next
raise next_item
File "/home/ly/anaconda3/envs/casa/lib/python3.6/site-packages/prefetch_generator/__init__.py", line 98, in run
for item in self.generator: self.queue.put((True , item))
File "/home/ly/anaconda3/envs/casa/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
data = self._next_data()
File "/home/ly/anaconda3/envs/casa/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
data = self._dataset_fetcher.fetch(index) # may raise StopIteration
File "/home/ly/anaconda3/envs/casa/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/home/ly/anaconda3/envs/casa/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/home/ly/test/CasA-master/CasA-master/pcdet/datasets/kitti/kitti_dataset.py", line 388, in __getitem__
data_dict = self.prepare_data(data_dict=input_dict)
File "/home/ly/test/CasA-master/CasA-master/pcdet/datasets/dataset.py", line 140, in prepare_data
**data_dict,
File "/home/ly/test/CasA-master/CasA-master/pcdet/datasets/augmentor/data_augmentor.py", line 182, in forward
data_dict = cur_augmentor(data_dict=data_dict)
File "/home/ly/test/CasA-master/CasA-master/pcdet/datasets/augmentor/database_sampler.py", line 417, in __call__
data_dict = self.add_sampled_boxes_to_scene(data_dict, sampled_gt_boxes, total_valid_sampled_dict)
File "/home/ly/test/CasA-master/CasA-master/pcdet/datasets/augmentor/database_sampler.py", line 334, in add_sampled_boxes_to_scene
sampled_gt_boxes, data_dict['road_plane'], data_dict['calib']
KeyError: 'road_plane'这个问题应该如何解决 感谢

> /pcdet/utils/common_utils.py中的init_dist_pytorch函数初始的过程注释掉一部分参数。如下： dist.init_process_group（ backend=backend， # init_method='tcp：//127.0.0.1：%d' % tcp_port， # rank=local_rank， # world_size=num_gpus )

**Comment by Karkers** [comment]
这个问题我没遇到过，可能是road_plane数据集的问题？或者是yaml里边 USE_RODEPLAN那个？
